---
- hosts: all
  roles:
    - common
    - ipython-notebook
  tasks:
    - name: Perform a safe upgrade
      apt: upgrade=safe update_cache=yes

    - name: 'Ensure opencv, tesseract and poppler are installed'
      apt: pkg={{item}} update_cache=yes cache_valid_time=3600
      with_items:
        - python-dev
        - tesseract-ocr
        - python-opencv
        - python-matplotlib
        # - libmagickwand-dev
        - poppler-utils

    - name: Download python-tesseract deb
      get_url: dest=/opt/ url=https://bitbucket.org/3togo/python-tesseract/downloads/python-tesseract_0.9-0.4ubuntu0_amd64.deb

    - name: Install python-tesseract deb
      command: chdir=/opt/ dpkg -i python-tesseract_0.9-0.4ubuntu0_amd64.deb creates=/usr/lib/python2.7/dist-packages/tesseract.py

# - name: 'Install Wand, python binding for ImageMagick'
#   pip: name=Wand
